package: rexstan
version: '1.0.5'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/rexstan

page:
    title: translate:name
    perm: admin
    icon: rex-icon fa-user-secret
    subpages:
        analysis: { title: translate:analysis }
        settings: { title: translate:settings }
        readme: { title: translate:readme, subPath: README.md }

console_commands:
    rexstan:analyze: rexstan_command

requires:
    php:
        version: '>=7.2'
    redaxo: ^5.2
