package: rexstan
version: '1.0.53'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/rexstan

page:
    title: translate:name
    perm: admin
    icon: rex-icon fa-user-secret
    popup: true
    linkAttr: { target: _rexstan }
    subpages:
        settings: { title: translate:settings }
        analysis: { title: translate:analysis }
        summary: { title: translate:summary }
        readme: { title: translate:readme, subPath: README.md }
        faq: { title: translate:faq, subPath: FAQ.md, icon: rex-icon fa-book }

console_commands:
    rexstan:analyze: rexstan_command

requires:
    php:
        version: '>=7.3, <8.3'
    redaxo: '^5.2'

installer_ignore:
    - phpstan.dev.neon
    - tests/
