package: rexstan
version: '1.0.116'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/rexstan

page:
    title: translate:name
    perm: admin
    icon: rexstan-navigation-icon
    popup: true
    linkAttr: { target: _rexstan }
    subpages:
        settings: { title: translate:settings }
        analysis:
            title: translate:analysis
            itemClass: 'use-loader'
        lint-analysis:
            title: translate:lint_analysis
            itemClass: 'use-loader'
        summary:
            title: translate:summary
            itemClass: 'use-loader'
        readme: { title: translate:readme, subPath: README.md }
        faq: { title: translate:faq, subPath: FAQ.md, icon: rex-icon fa-book }

console_commands:
    rexstan:analyze: rexstan\rexstan_command

requires:
    php:
        version: '>=7.4, <8.3'
    redaxo: '^5.2'

installer_ignore:
    - phpstan.dev.neon
    - tests
